import { NavSection } from '../types/navigation';

export const documentationSections: NavSection[] = [
  {
    id: 'shapes',
    title: 'Shapes',
    slug: '/docs/shapes',
    description: 'Geometric primitives, polylines, polygons, and high-order bezier/arc curves.',
    order: 1,
    available: true,
    icon: 'Shapes',
    items: [
      { id: 'shapes-intro', title: 'Introduction', path: '/docs/shapes#introduction' },
      { id: 'shapes-rect', title: 'Rectangle (Rect)', path: '/docs/shapes#rectangle' },
      { id: 'shapes-circle', title: 'Circle & Ellipse', path: '/docs/shapes#circle-ellipse' },
      { id: 'shapes-curves', title: 'Bezier & Arc Curves', path: '/docs/shapes#curves' },
      { id: 'shapes-api', title: 'Shape API Reference', path: '/docs/shapes#api-reference' },
    ],
  },
  {
    id: 'transformations',
    title: 'Transformations',
    slug: '/docs/transformations',
    description: 'Affine matrix transformations, translation, pivot rotation, scaling, and skewing.',
    order: 2,
    available: true,
    icon: 'Move',
    items: [
      { id: 'trans-intro', title: 'Affine Matrix Engine', path: '/docs/transformations#introduction' },
      { id: 'trans-translate', title: 'Translation', path: '/docs/transformations#translation' },
      { id: 'trans-rotation', title: 'Rotation & Pivot Modes', path: '/docs/transformations#rotation' },
      { id: 'trans-scaling', title: 'Scaling Properties', path: '/docs/transformations#scaling' },
      { id: 'trans-skew', title: 'Skew Angles', path: '/docs/transformations#skew' },
      { id: 'trans-batching', title: 'Batching (beginT / endT)', path: '/docs/transformations#batching' },
      { id: 'trans-playground', title: 'Interactive Engine', path: '/docs/transformations#playground' },
      { id: 'trans-api', title: 'Transformation API', path: '/docs/transformations#api-reference' },
    ],
  },
  {
    id: 'filters',
    title: 'Filters',
    slug: '/docs/filters',
    description: 'SVG visual effects pipeline including drop shadows, blurs, and color adjustments.',
    order: 3,
    available: true,
    icon: 'Sparkles',
    items: [
      { id: 'filters-intro', title: 'SVG Filter Pipeline', path: '/docs/filters#introduction' },
      { id: 'filters-shadow', title: 'Drop Shadow Filter', path: '/docs/filters#drop-shadow' },
      { id: 'filters-api', title: 'Filters API Reference', path: '/docs/filters#api-reference' },
    ],
  },
  {
    id: 'animation',
    title: 'Animation',
    slug: '/docs/animation',
    description: 'Continuous RequestAnimationFrame sampling, attribute interpolation, easing curves, and controls.',
    order: 4,
    available: true,
    icon: 'Zap',
    items: [
      { id: 'anim-intro', title: 'Animation Architecture', path: '/docs/animation#introduction' },
      { id: 'anim-props', title: 'Animatable Attributes', path: '/docs/animation#animatable-properties' },
      { id: 'anim-demo', title: 'Interactive Playground', path: '/docs/animation#interactive-demo' },
      { id: 'anim-easing', title: 'Easing Functions', path: '/docs/animation#easing-functions' },
      { id: 'anim-api', title: 'Animation API Reference', path: '/docs/animation#api-reference' },
    ],
  },
  {
    id: 'architecture',
    title: 'Architecture',
    slug: '/docs/architecture',
    description: 'Scene graph hierarchy, Canvas lifecycle, Engine RAF loop, and SVG reconciliation.',
    order: 5,
    available: true,
    icon: 'Cpu',
    items: [
      { id: 'arch-overview', title: 'System Overview', path: '/docs/architecture#overview' },
      { id: 'arch-canvas', title: 'Canvas & Scene Graph', path: '/docs/architecture#canvas-scene' },
      { id: 'arch-engine', title: 'Engine & Animation Loop', path: '/docs/architecture#engine-loop' },
      { id: 'arch-renderer', title: 'SVG DOM Reconciliation', path: '/docs/architecture#svg-renderer' },
    ],
  },
];
